// AfroSINT Nations Data
const atwAllCities=[
{iso:"dz",name:"Algeria",city:"Algiers",tz:"Africa/Algiers"},
{iso:"ao",name:"Angola",city:"Luanda",tz:"Africa/Luanda"},
{iso:"bj",name:"Benin",city:"Porto-Novo",tz:"Africa/Porto-Novo"},
{iso:"bw",name:"Botswana",city:"Gaborone",tz:"Africa/Gaborone"},
{iso:"bf",name:"Burkina Faso",city:"Ouagadougou",tz:"Africa/Ouagadougou"},
{iso:"bi",name:"Burundi",city:"Gitega",tz:"Africa/Bujumbura"},
{iso:"cm",name:"Cameroon",city:"Yaound\u00e9",tz:"Africa/Douala"},
{iso:"cv",name:"Cape Verde",city:"Praia",tz:"Atlantic/Cape_Verde"},
{iso:"cf",name:"Central African Republic",city:"Bangui",tz:"Africa/Bangui"},
{iso:"td",name:"Chad",city:"N'Djamena",tz:"Africa/Ndjamena"},
{iso:"km",name:"Comoros",city:"Moroni",tz:"Indian/Comoro"},
{iso:"cg",name:"Congo (Brazzaville)",city:"Brazzaville",tz:"Africa/Brazzaville"},
{iso:"cd",name:"Congo (Kinshasa)",city:"Kinshasa",tz:"Africa/Kinshasa"},
{iso:"ci",name:"C\u00f4te d'Ivoire",city:"Yamoussoukro",tz:"Africa/Abidjan"},
{iso:"dj",name:"Djibouti",city:"Djibouti",tz:"Africa/Djibouti"},
{iso:"eg",name:"Egypt",city:"Cairo",tz:"Africa/Cairo"},
{iso:"gq",name:"Equatorial Guinea",city:"Malabo",tz:"Africa/Malabo"},
{iso:"er",name:"Eritrea",city:"Asmara",tz:"Africa/Asmara"},
{iso:"sz",name:"Eswatini",city:"Mbabane",tz:"Africa/Mbabane"},
{iso:"et",name:"Ethiopia",city:"Addis Ababa",tz:"Africa/Addis_Ababa"},
{iso:"ga",name:"Gabon",city:"Libreville",tz:"Africa/Libreville"},
{iso:"gm",name:"Gambia",city:"Banjul",tz:"Africa/Banjul"},
{iso:"gh",name:"Ghana",city:"Accra",tz:"Africa/Accra"},
{iso:"gn",name:"Guinea",city:"Conakry",tz:"Africa/Conakry"},
{iso:"gw",name:"Guinea-Bissau",city:"Bissau",tz:"Africa/Bissau"},
{iso:"ke",name:"Kenya",city:"Nairobi",tz:"Africa/Nairobi"},
{iso:"ls",name:"Lesotho",city:"Maseru",tz:"Africa/Maseru"},
{iso:"lr",name:"Liberia",city:"Monrovia",tz:"Africa/Monrovia"},
{iso:"ly",name:"Libya",city:"Tripoli",tz:"Africa/Tripoli"},
{iso:"mg",name:"Madagascar",city:"Antananarivo",tz:"Indian/Antananarivo"},
{iso:"mw",name:"Malawi",city:"Lilongwe",tz:"Africa/Blantyre"},
{iso:"ml",name:"Mali",city:"Bamako",tz:"Africa/Bamako"},
{iso:"mr",name:"Mauritania",city:"Nouakchott",tz:"Africa/Nouakchott"},
{iso:"mu",name:"Mauritius",city:"Port Louis",tz:"Indian/Mauritius"},
{iso:"ma",name:"Morocco",city:"Rabat",tz:"Africa/Casablanca"},
{iso:"mz",name:"Mozambique",city:"Maputo",tz:"Africa/Maputo"},
{iso:"na",name:"Namibia",city:"Windhoek",tz:"Africa/Windhoek"},
{iso:"ne",name:"Niger",city:"Niamey",tz:"Africa/Niamey"},
{iso:"ng",name:"Nigeria",city:"Abuja",tz:"Africa/Lagos"},
{iso:"rw",name:"Rwanda",city:"Kigali",tz:"Africa/Kigali"},
{iso:"st",name:"S\u00e3o Tom\u00e9 and Pr\u00edncipe",city:"S\u00e3o Tom\u00e9",tz:"Africa/Sao_Tome"},
{iso:"sn",name:"Senegal",city:"Dakar",tz:"Africa/Dakar"},
{iso:"sc",name:"Seychelles",city:"Victoria",tz:"Indian/Mahe"},
{iso:"sl",name:"Sierra Leone",city:"Freetown",tz:"Africa/Freetown"},
{iso:"so",name:"Somalia",city:"Mogadishu",tz:"Africa/Mogadishu"},
{iso:"za",name:"South Africa",city:"Pretoria",tz:"Africa/Johannesburg"},
{iso:"ss",name:"South Sudan",city:"Juba",tz:"Africa/Juba"},
{iso:"sd",name:"Sudan",city:"Khartoum",tz:"Africa/Khartoum"},
{iso:"tz",name:"Tanzania",city:"Dodoma",tz:"Africa/Dar_es_Salaam"},
{iso:"tg",name:"Togo",city:"Lom\u00e9",tz:"Africa/Lome"},
{iso:"tn",name:"Tunisia",city:"Tunis",tz:"Africa/Tunis"},
{iso:"ug",name:"Uganda",city:"Kampala",tz:"Africa/Kampala"},
{iso:"zm",name:"Zambia",city:"Lusaka",tz:"Africa/Lusaka"},
{iso:"zw",name:"Zimbabwe",city:"Harare",tz:"Africa/Harare"},
{iso:"ag",name:"Antigua and Barbuda",city:"St. John's",tz:"America/Antigua"},
{iso:"bb",name:"Barbados",city:"Bridgetown",tz:"America/Barbados"},
{iso:"br",name:"Brazil",city:"Brasília",tz:"America/Sao_Paulo"},
{iso:"gd",name:"Grenada",city:"St. George's",tz:"America/Grenada"},
{iso:"gy",name:"Guyana",city:"Georgetown",tz:"America/Guyana"},
{iso:"jm",name:"Jamaica",city:"Kingston",tz:"America/Jamaica"},
{iso:"lc",name:"Saint Lucia",city:"Castries",tz:"America/St_Lucia"},
{iso:"tt",name:"Trinidad and Tobago",city:"Port of Spain",tz:"America/Port_of_Spain"}
];
